### ISSUE TITLE
Enable TLS client certificate verification

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#13749]
imported from https://www.assembla.com/spaces/akka/tickets/3749

from Nicholas Sterling:

There is an outstanding ticket in the Spray issue database for adding two-way SSL (certificate-based mutual authentication):

https://github.com/spray/spray/issues/138

Here's some additional background info:

https://groups.google.com/forum/#!msg/spray-user/1zwACzT5Vrs/rH-pJmh28FEJ

It would make our lives easier if this were available; could I ask what the status is?  I know you have lots of other work on your plates with the acquisition...

Specifically I think we need

* SSL renegotiation after having established SSL but setting the two-way SSL switch
* access to the "client" certificate to acquire the contained ID

We want our servers to be able to interact securely (including subject identity) without the use of explicit credentials.

*Update*: I (@jrudolph) broke this ticket up into three parts, that are now tracked as separate tickets:
 * [x] #18349 Provide TLS session details in custom TlsSessionInfo header
 * [x] #18350 Allow configuration of HTTP server to request client certificates
 * [ ] #18351 Implement TLS session renegotiation support for client certification authentication `<<< this was dropped for the time being due to lack of actual interest and rather high complexity ~ ktoso`

**Comment by jrudolph** [comment]
I would like to split this issue in two:

 1. support a flag that allows to request client certificates per server binding statically and introduce a header that exposes the certificate / TLS session to the application
 2. support the dynamic upgrade of a connection into a client-authenticated one by triggering a TLS renegotiation. The application could choose per request if a client certificate is needed in which case the response is hold back until the authenticity of the client has been renegotiated and verified. (AFAIU from what people have told me that the process is supposed to work)

It seems that even with 1. implemented you would be able to support conditional client authentication indirectly by redirecting to another server instance / binding / port which requires client authentication. Before implementing 2. it would be nice to have a specification for the renegotiation process that browsers seem to follow to make sure not to introduce any security leaks or other surprises.

WDYT?

**Comment by sirthias** [comment]
I like this proposal!
It makes sense to have client-cert verification as a static property of a binding, which circumvents the inflight-verification-trickyness altogether and offers a simple user API.

+1

**Comment by jrudolph** [comment]
Ping @drewhk, any feedback for this ticket?

**Comment by drewhk** [comment]
I like the static flag idea as a first step. As for the second step, I am not sure if this is well specified, but I think it is still useful to try to implement it.

**Comment by jrudolph** [comment]
I created three new tickets for each of the sub parts, see the updated ticket description above.

**Comment by ktoso** [comment]
Thanks @jrudolph, I marked them as `http:next` so we can see all tickets remaining under that tag (even though they're "sub tickets")

**Comment by rkuhn** [comment]
so, shall we consider this “solved enough”? @ktoso?

**Comment by ktoso** [comment]
Yeah, I think it's solved but not sure what to do about the PR – I don't think anyone has a strong opinion on it somehow.

**Comment by ktoso** [comment]
Triaged, want to ponder and close or make a new ticket with details to be done

**Comment by ktoso** [comment]
I believe this is fixed, mostly due to `ssl-config` and the one last missing bit, we decided to drop (the renegotiation bit).
