### ISSUE TITLE
Cleanup akka build files

### ISSUE THREAD

**Issue by 2m** [akka/akka#15031]
Following issues should be addressed:
* [ ] use new key definition methods `val myTask = taskKey[Int]("A (required) description of myTask.")`
* [ ] convert `<+=`, `<++=`, `~=` to `:=`, `+=`, `++=`
* [ ] there are some other depracations `Project.Initialize`, ... which should be removed
* [x] ~~replace `Unidoc.scala` with sbt-unidoc plugin~~ (done in #15059)
* [x] ~~separate project build logic to separate `scala` files~~ (done in #15113)
* [x] ~~separate project settings to separate `build.sbt` files~~ (done in #15145)
* [ ] move akka module project definitions to a root `build.sbt` file
* [ ] carefully remove duplication in `MultiNode.scala` so we do not trigger #15166 again
* [x] ~~deduplicate samples build definitions~~ (done in #16201)

Following issues should be addressed after moving streams to 2.3.x and finally master branch:
* ~~run java 8 projects like `akka-http-java8-tests` instead of using maven and extra-build-steps~~([discussion](https://github.com/akka/akka/pull/17072#discussion_r27130287))

**Comment by viktorklang** [comment]
This has been in progress for a looong time…

**Comment by rkuhn** [comment]
Yes, we need to prioritize it. The merge of Streams & HTTP will be a good opportunity to do the remaining refactorings.

**Comment by jaceklaskowski** [comment]
Hey @viktorklang @rkuhn While I'm currently mostly in Apache Spark repo, I can help here and there. Let me know what is needed - a general overview of the build or something more substantial? In other words, guide me! :) Thanks.

**Comment by ktoso** [comment]
Hi Jacek, some of the things to do are listed in the first comment here: https://github.com/akka/akka/issues/15031#issue-31959563

Perhaps @2m has some more insights what would be good to clean up.

Thanks in advance :)

**Comment by ktoso** [comment]
Shall we remove the in progress marker from this repo?
Maybe some community help could push it over the finish line.

// cc @2m

**Comment by 2m** [comment]
Even better: lets close this one. Remaining tasks here were to remove deprecated features from the current build. So I will create another ticket for that.

**Comment by ktoso** [comment]
Great, thanks!
