### ISSUE TITLE
High-level HTTP client support

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#16856]
#It would be convenient if akka-http would provide common high-level HTTP functionality similar to what a browser supports in its backend. This is a collection of all the things that would belong into this category. This is a metaticket and each subfeature has its own ticket.

 - [ ] connection pooling and configurable request queuing (provided by host-level API #15681)
 - [x] request-level API (#15906)
 - [ ] automatic redirection (#15990)
 - [x] automatic retry attempts (#16852)
 - [ ] try different IP addresses on retries (#16827)
 - [ ] HTTP proxy support (for HTTP: #16853, for HTTPS: #16153)
 - [ ] authentication data store (#16854)
 - [ ] cookie store (#16855)
 - [ ] response routing DSL (#15909)
 - [ ] request building should be polished and documented (https://github.com/akka/akka/issues/18550)
 - [ ] optional: response decompression (https://github.com/akka/akka/issues/16813)
 - [ ] optional: Add support for OAuth authentication #16857

**Comment by kanerogers** [comment]
Awesome. Looking forward to this.

**Comment by jvican** [comment]
Me too. Great and necessary features!
If you need any help, let me know and I will help.

**Comment by rkuhn** [comment]
Thanks for your offer to help, the core team will likely not get around to these anytime soon.

**Comment by ktoso** [comment]
Somewhat related to https://github.com/akka/akka/issues/18550

**Comment by ktoso** [comment]
For reference when designing the client side:

I bumped into very nice blog post which compared different Scala HTTP clients, among others Spray and Play: 
https://www.implicitdef.com/2015/11/19/comparing-scala-http-client-libraries.html
I agree with the article that "dead simple" should be a focus of the Client Side, and the awesome stuff should be additions.

**Comment by francisdb** [comment]
Could be a joined effort together with
https://github.com/playframework/playframework/issues/4297 ?

**Comment by ktoso** [comment]
Thanks for cross referencing to that ticket – I've commented there as well as you'll notice :-) 
We definitely want to share bits of code with WS, we'll see how exactly we'll be able to do that (it's SSL/TLS handling is excellent).

**Comment by hepin1989** [comment]
I just encounter this problem too,and then just try the AHC.A higher level like play-ws would be really helpful,the current `singleRequest` one is not that handy.for the Play-WS,I don't think that could be split out,but for later,maybe we could have two implement of play-ws,one for the AHC one and one for the AKKA based one,anyway there is a WSAPI.

For the client side there is https://github.com/eBay/parallec,which we may take a look too.

**Comment by ktoso** [comment]
> for the Play-WS,I don't think that could be split out,but for later

I think it is crucial we do this. _no one_ wants to re-implement the awesome work around SSL/TLS handling Will did in there. We, in Akka HTTP, are focusing to have a _solid_ basis to build APIs on - easy to use API comes next :-)

I'm not too sure about parallec, I skimmed the dependencies and it's somewhat of a weird mix. Also, its use case is very specific, not a general purpose Http Client I feel.

**Comment by hepin1989** [comment]
Yes,our team is continuse to using Play-WS like thing,we wrap it ourself for none-play project,and for akka-http I think it should support https://github.com/netty/netty-tcnative for OpenSSL-based SSLEngine implementation:).

**Comment by francisdb** [comment]
Exactly. Anybody that wants to create a library that needs to do http calls (reactive database driver, ...) needs to make a decision on what client to use. Currently it's a hard choice. Since there is no good default. I would love to use play-ws but it's to bloated with all it's dependencies.

**Comment by jeffpeiyt** [comment]
@ktoso Parallec does focus some large scale use cases (such as serving as agent master to manage a lot of agents or making a lot of concurrent calls). It  uses AHC and also supports TCP/PING/SSH, which may make the dependency looks mixed.

Probably @hepin1989 means that he likes Akka HTTP to have some level of built in concurrency control to handle large scale calls.

**Comment by ktoso** [comment]
comment via @2beaucoup:

> I can imagine that additional shortcuts like HTTP().get("http://akka.io/") could become handy. But that would be another alternative way of doing things. Oh my...

Yeah, however may be worth drafting a bit as experimental side/pet project in any case...

I toyed around with it and the nice idea about it is that fluent DSLs can lead towards doing only the right thing (also, not allow calling request unless dataBytes sink (or "please drain but i dont care") is defined etc. 

Another answer would be `WS` is we're able to make it have switchable impls and rip it out (which is in progress).

Up for grabs and opinions still I think...

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
