### ISSUE TITLE
Remove last todo-pages from akka-http docs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18012]
Hi all,
we have missed a number of TODO pages and released 1.0 without them - this is no good.

The pages are:

java:
- [x] stream-rate.rst -- 2m
- [x] http/client-side/connection-level.rst `// has scala-part`
- [x] http/client-side/host-level.rst `// has scala-part`
- [x] http/client-side/https-support.rst `// has scala-part`
- [x] http/client-side/request-level.rst `// has scala-part`
- [x] http/routing-dsl/handlers.rst `// mostly complete`
- [x] http/server-side/low-level-server-side-api.rst
- [x] http/server-side/websocket-support.rst

scala:
- [x] stream-rate.rst -- 2m
- [x] http/client-side/connection-level.rst
- [x] http/server-side/low-level-server-side-api.rst
- [ ] http/server-side/migration-from-spray.rst https://github.com/akka/akka/issues/17972
- [x] http/routing-dsl/directives/security-directives/index.rst `// TODO explain http in this picture`

common: 
- [x] http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/common/json-support.html
- [x] http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/common/marshalling.html
- [x] http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/common/unmarshalling.html
- [x] http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/common/de-coding.html
- [x] http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/common/json-support.html
- [x] http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/common/xml-support.html

additional (not needed asap):
- [ ] explain the magnet https://github.com/akka/akka/issues/17749

We should fix these ASAP, as it's kind of a screw up on our side with the 1.0... We'll start with those which have a scala side and need the java side (a few), but would need assistance for the others, can we count on you guys to help out here? // @jrudolph @sirthias

**Comment by ktoso** [comment]
Please ping the ticket here if working on any of these. // cc @2m

**Comment by 2m** [comment]
I am working on `stream-rate` scala+java

**Comment by sirthias** [comment]
I'll take care of the http stuff on the scala side.

**Comment by ktoso** [comment]
Thanks Mathias! We're thinking how to ship these now. 
On one hand, it's tempting to simply update the publisher 1.0 documentation - because we don't ship them in any other artifact except the webpage (anyone veto that?), otherwise it'd have to wait for a `1.0.1` or `1.1`.. Since

**Comment by hepin1989** [comment]
I think we should keep the online document updated asap.especially for the missed one.If the document have corresponding  side from the code,I think that would just fine.

**Comment by jrudolph** [comment]
I'm already working on Java-side testing documentation and will probably then move to the missing Java client-side docs.

**Comment by ktoso** [comment]
@jrudolph @sirthias There's 6 more pages in `common` which are missing; 
We really need this fixed ASAP, progress on docs was very slow recently, can we expect you guys to help out today?

**Comment by ktoso** [comment]
Some missing parts ported to java: https://github.com/akka/akka/pull/18019

**Comment by jrudolph** [comment]
@ktoso I'm working on the reamining java parts (the long hours last week and start of this week have taking a bit of a toll, though,  some things I needed to catch up with have slowed progress somewhat).

**Comment by ktoso** [comment]
Thanks for the update guys, don't mean to push too hard but wanted to get some estimate what we can expect and promise people about this.

**Comment by 2beaucoup** [comment]
There are some holes in the directives docs ([example](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/method-directives/extractMethod.html)) too.

IMO the docs are a bit too fine grained here. Maybe a page per trait would be a better fit? I.e. change the layout from `/directives/xxx-directives/index.rst` to `directives/xxx-directives.rst` and inline the directive doc in the trait page

There's redundancy with the scaladoc as well. Would it be possible to simply fetch the first introductory paragraph for a directive from scaladoc? This stuff looks hard to maintain otherwise... Could work for the traits, too.

**Comment by 2beaucoup** [comment]
One more thing: [Predefined Directives (alphabetically)](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/http/routing-dsl/directives/alphabetically.html) already contains descriptions which are missing in the details pages.  That makes it **3** times a description is duplicated (scaladoc, overview, detail page).

**Comment by jrudolph** [comment]
The missing bit of the java-side `http/server-side/low-level-server-side-api.rst` is actually missing the java-side API (`Http.serverLayer`), so what should we do with that? Create a ticket, so we can fix it before the next release? Or what's the current plan about how to release the doc fixes here?

**Comment by ktoso** [comment]
For the missing docs pages I was planning to push the docs to the `1.0` directory again, since it's not new APIs. Things where japi is missing will have to wait I guess - shall we remove the empty placeholders for the 1.0 re-push then, so it doesn't look as empty?

**Comment by jrudolph** [comment]
Yes, let's remove that section. I created #18027 to add API and docs for 1.1

**Comment by jrudolph** [comment]
Or maybe let's leave a remark that you can already use it from the Scala side and support will be added.

**Comment by 2m** [comment]
All of the issues mentioned here were fixed (instead of the migration guide) and documentaiton has been republished to http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/

**Comment by 2beaucoup** [comment]
:+1:

**Comment by ktoso** [comment]
Awesome, thanks everyone :-)
