### ISSUE TITLE
Release with jdk9

### ISSUE THREAD

**Issue by raboof** [akka/akka#23789]
Releasing currently is done from the #23651 branch but with some manual steps to compile jdk9-specific classes with jdk9, and the rest of the build with jdk8 for compatibility (see the `v2.5.6-preparations` branch for an example).

We'd want to automate this in sbt (probably using the [`--release` option for scalac](https://docs.oracle.com/javase/9/migrate/toc.htm))

**Comment by 2m** [comment]
The following are the remaining tasks to have a release with jdk9 back to the state as we had with jdk8:
* [ ] Build with JDK9 against the JDK8 API (#23755). Needs Scala 2.11.x and 2.12.x support for a javac like `--release` flag.
* [ ] Enable sbt-api-mappings (#23843). The plugin is cross-compiled, therefore it needs a new version of 0.13.x with jdk9 support. Revisit this after that sbt version is out.
* [ ] whitesource support (#23757).
* [ ] JavaDoc on JDK9 (#23756).
* [ ] Update Akka build to sbt 1.0.3 to get rid of Illegal Access errors while starting the build.

**Comment by mkurz** [comment]
Upgrade to sbt 1.0.3 might not be possible:
https://github.com/sbt/sbt/issues/3684

**Comment by ktoso** [comment]
Another thing to add: Before anything else we should already reserve a module name by the way, so users can use our not-yet-modular-jars as-if-modular. This is pretty simple, we just need to add metadata to the manifest:

```
Automatic-Module-Name: io.akka.actor
```

The module name should be reverse domain, so `io.akka` and then followed by akka sub-project name I guess, the names can't have 

See also:

> The naming issues are well-explained on Stephen Colebourne's blog:
> - http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html
> - http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html <- the explanation of module hell problem

Esp. read the module hell one ☝️ 

via https://github.com/mockito/mockito/issues/1189

**Comment by raboof** [comment]
Added `Automatic-Module-Name` as a separate ticket in https://github.com/akka/akka/issues/23931

**Comment by 2m** [comment]
My current work-in-progress branch: https://github.com/akka/akka/commits/wip-jdk9-build-2m

And the PR validator that I used to test this branch: https://jenkins.akka.io:8498/job/pr-validator-akka-java-9/

The only change needed for the WIP branch that I remember now is to change the hardcoded path to rt.jar (`/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar`) to something that discovers the jar across different os'es (Linux, MacOS) and setups (dev computers, PR validation machines). For that we have some branch from the Lisbon hackathon (I know, what a mess).

**Comment by 2m** [comment]
PR to sbt that will make it possible to automatically discover `rt.jar`: https://github.com/sbt/sbt/pull/4136

**Comment by patriknw** [comment]
This has been done
