### ISSUE TITLE
General Typed docs cleanup after all API changes

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24717]
* [x] Remove mention of Typed and Untyped everywhere
  * [x] https://github.com/akka/akka/pull/27617 Somewhere it's needed to make the difference clear, and then it should be Typed/Classic
  * [x] https://github.com/akka/akka/pull/27627 Remove mention of Untyped everywhere  
  * [x] https://github.com/akka/akka/pull/27819 A few more removals
  *  [x] https://github.com/akka/akka/pull/27622 Scaladoc: Change "Untyped" to "Classic"
  * Akka Typed won't mean much to anyone who doesn't know the historical context
* [x] #27765 Update General Concepts with Akka Typed as primary target. Might need some notes of where there are differences (if they are important).
* [x] Swap content from Classic pages to Typed. We don't want full copy of both so best if full information is in the Typed pages and keeping the Classic pages for specific example snippets and links to the Typed content.
  * [x] #27708 Cluster Usage. Merge this before starting:
     - [x] #27801 Cluster Singleton
     - [x] #27764 Cluster Sharding 
     - [x] #27783 Distributed Data 
  * [x] https://github.com/akka/akka/pull/27762 Serialization, also move example that is in typed/cluster.md
   * [x] https://github.com/akka/akka/pull/27779 Classic Persistence can probably be as is, but some content should maybe be incorporated in Persistence Typed also to make it complete
   * [x] #27866 Classic Actors can probably be as is, but some content should maybe be incorporated in Actors Typed also to make it complete
* Update doc snippets according to Style Guide, typical things:
  - Prefer AbstractBehavior for Java
  - extract lambdas to methods
  - apply/create name of factory method
  - [x] https://github.com/akka/akka/pull/27616 actor-discovery.md
  - [x] https://github.com/akka/akka/pull/27543 actor-lifecycle.md
  - [x] https://github.com/akka/akka/pull/27541 actors.md
  - [x] https://github.com/akka/akka/pull/27613 cluster-sharding.md
  - [x] https://github.com/akka/akka/pull/27615 cluster-singleton.md
  - [x] https://github.com/akka/akka/pull/27612 cluster.md
  - [x] https://github.com/akka/akka/pull/27542 coexisting.md
  - [x] https://github.com/akka/akka/pull/27748 dispatchers.md
  - [x] https://github.com/akka/akka/pull/27659 distributed-data.md
  - [x] https://github.com/akka/akka/pull/27624 fault-tolerance.md
  - [x] https://github.com/akka/akka/pull/27746 fsm.md
  - [x] https://github.com/akka/akka/pull/27596 getted started guide
  - [x] https://github.com/akka/akka/pull/27597 interaction-patterns.md
  - [x] mailboxes.md
  - [x] https://github.com/akka/akka/pull/27717 persistence.md, persistence-snapshot.md, persistence-style.md
  - [x] https://github.com/akka/akka/pull/27623 routers.md
  - [x] https://github.com/akka/akka/pull/27619 stash.md
  - [x] stream.md
  - [x] https://github.com/akka/akka/pull/27750 testing.md
* [x] #27771 Section about ActorSystem
  * seems to still be some confusion around Typed vs. Untyped ActorSystem
  * start things inside the user guardian behavior, rather than from the outside (maybe also add to style guide)
* [x] #27784 Cross link also from Typed doc pages to Classic, because most people land in the docs from a Google search or link from a blog post (do after #27708 at least)
  * main thing is to try to quickly route everyone to the right place
* [x]  https://github.com/akka/akka/pull/27540 the "Relation to Akka (untyped) Actors" section probably needs a little rework
  * maybe move to Coexistence or Classic section
* [x] #27818 Add HTML meta page descriptions for the most important landing pages
  * See https://github.com/akka/alpakka-kafka/pull/889/files
* [x] Don't start a page with referencing and describing how it works in Classic
  * [x] #27880 "Actor discovery" starts by referencing the way you do it in untyped actors, which is only useful when that's something you already understand. Still worth noting, maybe just not as the first thing.
  * [x] #27901 The "Streams" page under the (typed) "Actors" section is positioned as an alternative rather than the default. The whole page should be integrated into the main "Streams" section.
  * [x] "Behaviors as Finite state machines", "Persistence", "Cluster", "Cluster Sharding" and others also start by referencing untyped.

**Comment by hepin1989** [comment]
We may want to *waiting* a little longger to mark it `FINAL`:)

**Comment by patriknw** [comment]
* [ ] Update General Concepts with Akka Typed as primary target. Might need some notes of where there are differences (if they are important).
* [ ] Swap content from Classic pages to Typed. We don't want full copy of both so best if full information is in the Typed pages and keeping the Classic pages for specific example snippets and links to the Typed content.
  * [ ] Cluster Usage
  * [ ] Cluster Singleton
  * [ ] Cluster Sharding
  * [ ] Distributed Data
  * [ ] Classic Persistence can probably be as is, but some content should maybe be incorporated in Persistence Typed also to make it complete
  * [ ] Classic Actors can probably be as is, but some content should maybe be incorporated in Actors Typed also to make it complete

**Comment by patriknw** [comment]
Related to https://github.com/akka/akka/issues/27223

**Comment by chbatey** [comment]
* [ ] Switch extensions page for typed and move old to classic section

**Comment by patriknw** [comment]
@helena @raboof The ddata docs task we talked about is here. In the Typed docs cleanup. See "Swap content from Classic pages to Typed" above.

**Comment by helena** [comment]
Thanks @patriknw

**Comment by helena** [comment]
* [ ] Update samples for typed cluster join used in classic cluster doc

**Comment by helena** [comment]
https://github.com/akka/akka/pull/27708 cluster - Swap content from Classic pages to Typed

**Comment by helena** [comment]
If time allows, add snippets for sharding send with envelope and extractor. And see if we can move more from sharding class to typed around sending to shard and allocation/location.

**Comment by helena** [comment]
https://github.com/akka/akka/issues/25997

**Comment by helena** [comment]
Closing, great team effort.

**Comment by patriknw** [comment]
Great work with this homongous ticket, @helena
