### ISSUE TITLE
[Overarching] Fix compiler warnings  

### ISSUE THREAD

**Issue by helena** [akka/akka#26088]
* Will cover a module by module effort with sub tickets for the specific modules being committed, for cleaner merges
* Will not cover deprecation warnings - some are there for reminders or binary compatibility
* Some warnings will remain, e.g. local var warnings needed and those marked with
```HERE BE DRAGONS``` - we hope to silence those through #26389

Broken out per subproject:

* [x] akka-actor* #26089
* [x] akka-remote* and akka-actor-typed #26138
* [x] akka-cluster* #26087
* [x] akka-distributed-data #26542
* [x] akka-protobuf #26582
* [x] akka-cluster-tools  https://github.com/akka/akka/pull/26647
* [x] akka-cluster-sharding https://github.com/akka/akka/pull/26648
* [x] akka-persistence https://github.com/akka/akka/pull/26654
* [x] akka-stream* https://github.com/akka/akka/pull/26673
* [x] akka-testkit* https://github.com/akka/akka/issues/26708
* [x] akka-actor-tests https://github.com/akka/akka/pull/26685
* [x] akka-remote-tests https://github.com/akka/akka/pull/26685
* [x] akka-slf4j https://github.com/akka/akka/pull/26678
* [x] akka-cluster-metrics https://github.com/akka/akka/pull/26678
* [x] akka-actor-typed #26738 
* [x] akka-actor-testkit-typed #26741 
* [x] akka-cluster  https://github.com/akka/akka/pull/26739
* [x] akka-cluster-sharding-typed https://github.com/akka/akka/pull/26747
* [x] akka-multi-node-testkit #26754
* [x] akka-osgi #26736 
* [x] akka-persistence-typed https://github.com/akka/akka/pull/26748
* [x] akka-persistence-query https://github.com/akka/akka/pull/26749
* [x] akka-remote #26735 
* [x] akka-stream-testkit #26751 
* [x] akka-testkit #26752 

Probably OK to postpone:
* [ ] akka-actor-typed-tests
* [ ] akka-bench-jmh
* [ ] akka-bench-jmh-typed
* [ ] akka-docs *
* [ ] akka-persistence-tck
* [ ] akka-stream-tests
* [ ] akka-stream-tests-tck

**Comment by chbatey** [comment]
Let's close this :) Can raise a new issue if we feel like doing the other ones

**Comment by helena** [comment]
Bueno
